name             'mysql-fabric'
maintainer       'Hisashi kOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures mysql-fabric'
long_description 'Installs/Configures mysql-fabric'
version          '0.1.0'
supports         'ubuntu', '= 14.04'
